stages:
  - test

test:haskell:
  stage: test
  image: "haskell:9.6.7"
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /haskell/i'
  script:
    - cabal --verbose=0 update
    - cabal --verbose=0 test

test:java:
  stage: test
  image: maven:3.9.6-eclipse-temurin-21
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /java/i'
  script:
    - mvn test

test:python:
  stage: test
  image: python:3.12
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /python/i'
  script:
    - pip install --upgrade pip
    - pip install pytest
    - python3 -m pytest -v
