version: 2.1

jobs:
  haskell_setup:
    docker:
      - image: haskell:9.6.7
    steps:
      - checkout
      - run:
          name: Update package list
          command: cabal --verbose=0 update
      - run:
          name: Run tests
          command: cabal --verbose=0 test
  java_setup:
    docker:
      - image: maven:3.9.9-eclipse-temurin-21-noble
    steps:
      - checkout
      - run:
          name: Run tests
          command: mvn test
  python-setup:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m pip install --upgrade pip
            pip install pytest
      - run:
          name: Run tests
          command: python3 -m pytest -v

workflows:
  version: 2
  haskell_test:
    jobs:
      - test
          filters:
            branches:
              only: /.*haskell.*/
  java_test:
    jobs:
      - test:
          filters:
            branches:
              only: /.*java.*/
  python_test:
    jobs:
      - test:
          filters:
            branches:
              only: /.*python.*/
