name: Haskell Cabal Tests

on:
  push:
    branches:
      - '*trial*'
  pull_request:
    branches:
      - '*trial*'

jobs:
  test:
    runs-on: haskell:slim-bullseye

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Cabal package list
        run: cabal update --verbose=0

      - name: Run Cabal tests
        run: cabal test --verbose=0
